#
# BungeeMail is a mail system for bungeecord
# It's probably similar to essentials /mail
#

# Text Format
# ===========
#
# You can create links and access other formatting options with a syntax similar to bbcode. Vanilla color codes still
# work.
#
# For example [b]this is bold[/b], [i]this is italic[/i], [u]this is underlined[/u] and [s]this is crossed out[/s].
# The difference between the above and making something &lbold&r the vanilla way is, that the above makes all the
# enclosed text bold, while &l makes bold everything until reaching the next color code.
# Same for [color=...]
#
# How links will work is easy to guess, e.g. it's just [url]spigotmc.org[/url] or [url=spigotmc.org]click here[/url].
# Executing commands works similar [command=/tp CodeCrafter47]click here[/command].
#
# Suggesting commands works with [suggest=/tp ]...[/suggest]
# To create tooltips d [hover=Text magically appears when moving the mouse over]this[/hover].
#
# It is possible to use [nocolor][/nocolor] to prevent the use of legacy color codes in a block;
# [nobbcode][/nobbcode] will prevent the use of bbcode in a block;

# whether clickable things in chat are to be underlined
underlineLinks: true

# Command used for sending/ reading mails, etc.
# if you change this to "gmail" players have to use /gmail send ... instead of /mail send ...
mail_command: mail

# Messages
noNewMessages: "&eYou don't have any new messages"
listallHeader: "&9[==== Showing %start% to %end% of %max% mails === [command=/mail listall %next%]next[/command] ====]"
listHeader: "&9[==== Showing %visible% of %max% messages. [command=/mail list]more[/command] ====]"
oldMessage: "&7From %sender%: &f%message%    &o&6[suggest=/mail del %id%]delete[/suggest]"
newMessage: "&6From %sender%: &f%message%    &o&6[suggest=/mail %sender%]reply[/suggest]"
receivedNewMessage: "&cYou just received a new mail. Type [command]/mail list[/command] to see it."
messageSent: "&aYour mail has been sent successfully."
messageSentToAll: "&aYou just sent %num% mails."
unknownTarget: "&cUnknown target: You may only send mails to players which have played on the server before."
help: |-
  &b[suggest]/mail help[/suggest] &eshows this cool help page
  &b[suggest]/mail list[/suggest] &eshows new mails
  &b[suggest]/mail listall[/suggest] &eshows all mails (also ones that you have already read)
  &b[suggest=/mail ]/mail <player> <message>[/suggest] &esend a mail
  &b[suggest=/mail sendall ]/mail sendall <message>[/suggest] &esend [b]many[/b] mails :D
  &b[suggest=/mail del ]/mail del all|read|#[/suggest] &edelete mails
wrongSyntax:
  list: &cWrong syntax! Use &b[suggest=/mail list ]/mail list <page>[/suggest]
  listall: &cWrong syntax! Use &b[suggest=/mail listall ]/mail listall <page>[/suggest]
noPermission: "&cYou. Don't. Have. Permission."
deletedSingle: "&aYou deleted 1 message."
deletedRead: "&aYou deleted all old mails."
deletedAll: "&aYou deleted all mails."
commandError: "&cAn error occurred while processing your command: %error%"
emptyMail: "&cYou can't send empty mails."

# Login
showMailsOnLogin: true
# this is shown on login if the above is false; otherwise the player is shown the output of /mail view directly
loginNewMails: "&aYou have %num% new mails. Type [i][command]/mail view[/command][/i] to read them."

# show the player the same info as on login when he changes to another server
showMailsOnServerSwitch: true

# SQL Connection information
# if you set useMySQL to false all data will be stored in a flatfile
useMySQL: false

# if you set useMySQL to true please enter valid connection inormation
mysql_hostname: localhost
mysql_port: 3306
mysql_database: minecraft
mysql_username: root
mysql_password: superSecretPassword

# automatically cleanup database
# deletes all read mails older than cleanup_threshold days
cleanup_enabled: true
cleanup_threshold: 7
